name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory: [ './src' ]
        python-version: ['3.12', '3.11', '3.10']
    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}
        python-version: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/actions/setup-repo
        with:
          working-directory: ${{ matrix.working-directory }}
          python-version: ${{ matrix.python-version }}
      
      - name: lint
        run: make lint
      # - name: test :) 
      #   run: make test
